import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import AuthContext from "./authcontext";
import { ReactElement } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col sm:mx-36 mx-8 antialiased bg-slate-900`}
      >
        <div className="flex flex-col h-screen">
          <AuthContext>
            <Header />
            <div className="flex-1 items-center justify-center flex">
              {children}
            </div>
          </AuthContext>
        </div>
      </body>
    </html >
  );
}
